# -*- coding: utf-8 -*-
"""advisory_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2cCdCC5LIwYqh6-h3rQtHs1ReGPmVTg
"""

# 1. Install import-ipynb package
!pip install -q import-ipynb

# 2. Import the module and extract STOCK_UNIVERSE
import import_ipynb
from stock_universe import STOCK_UNIVERSE

# 3. Test that the universe loaded correctly
print("Loaded tickers:", list(STOCK_UNIVERSE.keys()))

import math
import import_ipynb
from stock_universe import STOCK_UNIVERSE

# Macroeconomic / Market Parameters
R_F = 0.04  # Risk-free rate (4%)
E_RM = 0.10  # Expected market return (10%)
PAIRWISE_RHO = 0.3  # Pairwise correlation coefficient (rho = 0.3)


# -----------------------------------------------------------------------------
# STAGE 2: ACT (Tool Function)
# -----------------------------------------------------------------------------
def get_stock_data(ticker: str) -> dict:
    """Look up beta, analyst_expected_return, and std_dev from STOCK_UNIVERSE."""
    if ticker not in STOCK_UNIVERSE:
        raise ValueError(f"Ticker '{ticker}' not found in STOCK_UNIVERSE.")
    return STOCK_UNIVERSE[ticker]


# -----------------------------------------------------------------------------
# AGENT LOOP IMPLEMENTATION
# -----------------------------------------------------------------------------
def run_advisory_agent(investor_profile: dict) -> dict:
    investor_id = investor_profile.get("id", "UNKNOWN")
    risk_tolerance = (
        investor_profile.get("risk_tolerance", "").strip().capitalize()
    )

    # =========================================================================
    # STAGE 1: THINK (Required Prescribed Allocation Table)
    # =========================================================================
    if risk_tolerance == "Conservative":
        tickers = ["PAYBOND", "PAYGOLD", "PAYRETAIL"]
    elif risk_tolerance == "Moderate":
        tickers = ["PAYRETAIL", "PAYINFRA", "PAYGOLD"]
    elif risk_tolerance == "Aggressive":
        tickers = ["PAYTECH", "PAYFIN", "PAYINFRA"]
    else:
        raise ValueError(
            f"Invalid or unsupported risk tolerance: '{risk_tolerance}'"
        )

    # Prescribed equal weights (1/3 each)
    weights = [1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0]

    # =========================================================================
    # STAGE 2: ACT (Tool Call Execution)
    # =========================================================================
    stock_data_list = [get_stock_data(t) for t in tickers]

    # =========================================================================
    # STAGE 3: OBSERVE -> DECIDE (CAPM Return & Portfolio Variance Math)
    # =========================================================================
    # 1. CAPM-Expected Return per stock using ONLY beta: E(R) = R_f + beta * (E(R_m) - R_f)
    capm_returns = [
        R_F + data["beta"] * (E_RM - R_F) for data in stock_data_list
    ]

    # Portfolio Expected Return (weight-averaged across the 3 tickers)
    portfolio_expected_return = sum(
        w * r for w, r in zip(weights, capm_returns)
    )

    # 2. Portfolio Variance Formula:
    #    Var(R_p) = sum_i (w_i^2 * sigma_i^2) + 2 * sum_{i<j} (w_i * w_j * Cov(R_i, R_j))
    #    with Cov(R_i, R_j) = rho * sigma_i * sigma_j
    sigmas = [data["std_dev"] for data in stock_data_list]

    # Direct Variance Component: sum(w_i^2 * sigma_i^2)
    var_direct = sum((w**2) * (s**2) for w, s in zip(weights, sigmas))

    # Covariance Component: 2 * sum_{i<j} (w_i * w_j * rho * sigma_i * sigma_j)
    cov_terms = 0.0
    for i in range(len(sigmas)):
        for j in range(i + 1, len(sigmas)):
            cov_terms += (
                2
                * weights[i]
                * weights[j]
                * (PAIRWISE_RHO * sigmas[i] * sigmas[j])
            )

    portfolio_variance = var_direct + cov_terms

    # Convert variance to portfolio standard deviation
    portfolio_std_dev = math.sqrt(portfolio_variance)

    # =========================================================================
    # HUMAN-IN-THE-LOOP ESCALATION CHECK
    # =========================================================================
    # If computed portfolio standard deviation exceeds 20% (0.20), escalate to human advisor
    if portfolio_std_dev > 0.20:
        status = "ESCALATED_TO_HUMAN_ADVISOR"
    else:
        status = "FINALIZED"

    # Return output dictionary with all computed numbers attached
    return {
        "investor_id": investor_id,
        "risk_tolerance": risk_tolerance,
        "prescribed_allocation": dict(zip(tickers, weights)),
        "portfolio_capm_expected_return": portfolio_expected_return,
        "portfolio_std_dev": portfolio_std_dev,
        "portfolio_std_dev_pct": f"{portfolio_std_dev * 100:.2f}%",
        "status": status,
    }


# -----------------------------------------------------------------------------
# Batch Verification Run
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    test_investors = [
        {"id": "INV01", "risk_tolerance": "Conservative"},
        {"id": "INV02", "risk_tolerance": "Moderate"},
        {"id": "INV03", "risk_tolerance": "Aggressive"},
        {"id": "INV04", "risk_tolerance": "Moderate"},
        {"id": "INV05", "risk_tolerance": "Aggressive"},
    ]

    print("=" * 75)
    print(
        f"{'ID':<8} | {'Risk Tier':<13} | {'Port. Volatility':<16} | {'Status Flag'}"
    )
    print("=" * 75)

    for profile in test_investors:
        result = run_advisory_agent(profile)
        print(
            f"{result['investor_id']:<8} | "
            f"{result['risk_tolerance']:<13} | "
            f"{result['portfolio_std_dev_pct']:<16} | "
            f"{result['status']}"
        )
    print("=" * 75)

import math
import os
import import_ipynb
from stock_universe import STOCK_UNIVERSE

# Environment Control Flag
MOCK_LLM = int(os.getenv("MOCK_LLM", 1))

# Macroeconomic & Market Parameters
R_F = 0.04  # Risk-free rate (4%)
E_RM = 0.10  # Expected market return (10%)
PAIRWISE_RHO = 0.3  # Correlation coefficient (rho = 0.3)


# Tool Call Simulation
def get_stock_data(ticker: str) -> dict:
    if ticker not in STOCK_UNIVERSE:
        raise ValueError(f"Ticker '{ticker}' not found in STOCK_UNIVERSE.")
    return STOCK_UNIVERSE[ticker]


# Agent Loop Execution
def run_advisory_agent(investor_profile: dict, mock_llm: int = MOCK_LLM) -> dict:
    investor_id = investor_profile.get("id", "UNKNOWN")
    risk_tolerance = (
        investor_profile.get("risk_tolerance", "").strip().capitalize()
    )

    # STAGE 1: THINK (Allocation Mapping)
    if risk_tolerance == "Conservative":
        tickers = ["PAYBOND", "PAYGOLD", "PAYRETAIL"]
    elif risk_tolerance == "Moderate":
        tickers = ["PAYRETAIL", "PAYINFRA", "PAYGOLD"]
    elif risk_tolerance == "Aggressive":
        tickers = ["PAYTECH", "PAYFIN", "PAYINFRA"]
    else:
        raise ValueError(f"Unsupported risk tolerance: {risk_tolerance}")

    weights = [1.0 / 3.0] * 3  # Equal weight across 3 tickers

    # STAGE 2: ACT (Tool Calls)
    stock_data_list = [get_stock_data(t) for t in tickers]

    # STAGE 3: OBSERVE -> DECIDE (CAPM & Risk Calculations)
    # 1. CAPM-Expected Return per stock using ONLY beta
    capm_returns = [
        R_F + data["beta"] * (E_RM - R_F) for data in stock_data_list
    ]
    portfolio_return = sum(w * r for w, r in zip(weights, capm_returns))

    # 2. Portfolio Variance & Standard Deviation with rho = 0.3
    sigmas = [data["std_dev"] for data in stock_data_list]
    var_direct = sum((w**2) * (s**2) for w, s in zip(weights, sigmas))
    cov_terms = sum(
        2 * weights[i] * weights[j] * (PAIRWISE_RHO * sigmas[i] * sigmas[j])
        for i in range(len(sigmas))
        for j in range(i + 1, len(sigmas))
    )
    portfolio_variance = var_direct + cov_terms
    portfolio_std_dev = math.sqrt(portfolio_variance)

    # Human-in-the-loop Escalation Check
    status = (
        "ESCALATED_TO_HUMAN_ADVISOR" if portfolio_std_dev > 0.20 else "FINALIZED"
    )

    # Narrative Sentence Generation (Gated by MOCK_LLM)
    tickers_str = ", ".join(tickers)
    if mock_llm == 1:
        narrative = (
            f"For {risk_tolerance} investor {investor_id}, we recommend an allocation across "
            f"{tickers_str} with an expected portfolio return of {portfolio_return:.1%} "
            f"and volatility of {portfolio_std_dev:.1%}."
        )
    else:
        # Extension mode for LLM generation
        narrative = f"Natural language summary for investor {investor_id} across {tickers_str}."

    return {
        "investor_id": investor_id,
        "risk_tolerance": risk_tolerance,
        "tickers": tickers_str,
        "expected_return": portfolio_return,
        "volatility": portfolio_std_dev,
        "status": status,
        "narrative": narrative,
    }


# Run all 5 investor profiles
if __name__ == "__main__":
    test_investors = [
        {"id": "INV01", "risk_tolerance": "Conservative"},
        {"id": "INV02", "risk_tolerance": "Moderate"},
        {"id": "INV03", "risk_tolerance": "Aggressive"},
        {"id": "INV04", "risk_tolerance": "Moderate"},
        {"id": "INV05", "risk_tolerance": "Aggressive"},
    ]

    for inv in test_investors:
        res = run_advisory_agent(inv)
        print(f"ID: {res['investor_id']} | Status: {res['status']}")
        print(f"Narrative: {res['narrative']}\n")

