# -*- coding: utf-8 -*-
"""dcf_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPJpRmA7TNjQxeiTXKECkjg4Q1zEyyNs
"""

import pandas as pd


def calculate_dcf_valuation():
    # 1. Base Inputs
    ebit = 1000.0
    tax_rate = 0.25
    dna = 150.0
    capex = 200.0
    delta_nwc = 50.0

    # Base FCFF calculation
    fcff_base = ebit * (1 - tax_rate) + dna - capex - delta_nwc  # ₹650.0 Mn

    # WACC Calculation using PAYRETAIL Beta = 0.85
    r_f, e_rm, beta = 0.04, 0.10, 0.85
    r_e = r_f + beta * (e_rm - r_f)  # 9.10%
    w_e, w_d, r_d_after_tax = 0.80, 0.20, 0.06
    wacc_base = (w_e * r_e) + (w_d * r_d_after_tax)  # 8.48%

    # Growth Profile
    growth_rates = [0.12, 0.10, 0.08, 0.06, 0.04]
    g_terminal_base = 0.03  # 3.0%

    # 2. Project 5 Years of FCFF
    projected_fcff = []
    curr_fcff = fcff_base
    for g in growth_rates:
        curr_fcff *= 1 + g
        projected_fcff.append(curr_fcff)

    # 3. Base DCF Valuation
    pv_fcff = [
        fcff / ((1 + wacc_base) ** i)
        for i, fcff in enumerate(projected_fcff, 1)
    ]
    sum_pv_fcff = sum(pv_fcff)

    tv_base = (projected_fcff[-1] * (1 + g_terminal_base)) / (
        wacc_base - g_terminal_base
    )
    pv_tv_base = tv_base / ((1 + wacc_base) ** 5)
    ev_dcf_base = sum_pv_fcff + pv_tv_base

    # 4. Sensitivity Grid (3x3: WACC vs Terminal Growth)
    wacc_grid = [wacc_base - 0.01, wacc_base, wacc_base + 0.01]
    g_grid = [g_terminal_base - 0.01, g_terminal_base, g_terminal_base + 0.01]

    sensitivity_matrix = []
    for w in wacc_grid:
        row = []
        for g in g_grid:
            pv_f = sum(
                [
                    fcff / ((1 + w) ** i)
                    for i, fcff in enumerate(projected_fcff, 1)
                ]
            )
            tv = (projected_fcff[-1] * (1 + g)) / (w - g)
            pv_tv = tv / ((1 + w) ** 5)
            row.append(round(pv_f + pv_tv, 2))
        sensitivity_matrix.append(row)

    sens_df = pd.DataFrame(
        sensitivity_matrix,
        index=[f"WACC {w:.2%}" for w in wacc_grid],
        columns=[f"Terminal g {g:.2%}" for g in g_grid],
    )

    # 5. EV/EBITDA Multiples Cross-Check
    ebitda = ebit + dna  # ₹1,150.0 Mn
    ev_ebitda_multiple = 12.0
    ev_multiples = ebitda * ev_ebitda_multiple  # ₹13,800.0 Mn

    return {
        "fcff_base": fcff_base,
        "wacc_base": wacc_base,
        "ev_dcf_base": ev_dcf_base,
        "sensitivity_table": sens_df,
        "ev_multiples": ev_multiples,
    }


if __name__ == "__main__":
    res = calculate_dcf_valuation()
    print(f"Base DCF Enterprise Value: ₹{res['ev_dcf_base']:,.2f} Mn")
    print(f"\n3x3 Sensitivity Matrix:\n{res['sensitivity_table']}")
    print(
        f"\n12x EV/EBITDA Multiples Valuation: ₹{res['ev_multiples']:,.2f} Mn"
    )