# -*- coding: utf-8 -*-
"""EDA_Pre-processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPe7ltmbX-5zaaaIR5BrMs7b5zlpV8Tx
"""

import pandas as pd

# 1. Load the dataset
df = pd.read_csv("credit_applicants.csv")

# Compute exact default rate (assuming column name is 'default')
default_rate = df["default"].mean() * 100

# Compute exact percentage of missing credit_bureau_score values
missing_bureau_pct = df["credit_bureau_score"].isna().mean() * 100

print(f"Measured Default Rate: {default_rate:.2f}%")
print(f"Missing Credit Bureau Score Percentage: {missing_bureau_pct:.2f}%")

# Engineer binary is_thin_file flag (1 where missing, 0 otherwise)
df["is_thin_file"] = df["credit_bureau_score"].isna().astype(int)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df["is_thin_file"] = df["credit_bureau_score"].isna().astype(int)

# Separate features and target (exclude non-predictive IDs)
X = df.drop(columns=["default", "applicant_id"])
y = df["default"]

# 2. Stratified Train/Test Split (75/25, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=42
)

# 3. Median Imputation (Training data only)
train_bureau_median = X_train["credit_bureau_score"].median()
X_train["credit_bureau_score"] = X_train["credit_bureau_score"].fillna(
    train_bureau_median
)
X_test["credit_bureau_score"] = X_test["credit_bureau_score"].fillna(
    train_bureau_median
)

# 4. Encode Categorical Features (One-Hot Encoding)
X_train = pd.get_dummies(X_train, columns=["employment_type"], drop_first=True)
X_test = pd.get_dummies(X_test, columns=["employment_type"], drop_first=True)
X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

# 5. Feature Scaling (Fit on Train only, Transform both)
scaler = StandardScaler()
X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index
)
X_test_scaled = pd.DataFrame(
    scaler.transform(X_test), columns=X_test.columns, index=X_test.index
)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.tree import DecisionTreeClassifier

# 1. Initialize and train Logistic Regression
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train_scaled, y_train)

# Predict class labels and probabilities
lr_preds = lr_model.predict(X_test_scaled)
lr_probs = lr_model.predict_proba(X_test_scaled)[:, 1]

# 2. Initialize and train Decision Tree Classifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_scaled, y_train)

# Predict class labels and probabilities
dt_preds = dt_model.predict(X_test_scaled)
dt_probs = dt_model.predict_proba(X_test_scaled)[:, 1]

# Evaluate models
print("Logistic Regression ROC-AUC:", roc_auc_score(y_test, lr_probs))
print("Decision Tree ROC-AUC:", roc_auc_score(y_test, dt_probs))

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)

# Compute Confusion Matrices
cm_lr = confusion_matrix(y_test, lr_preds)
cm_dt = confusion_matrix(y_test, dt_preds)

# Calculate Summary Metrics
results = pd.DataFrame(
    {
        "Metric": [
            "Confusion Matrix [TN, FP, FN, TP]",
            "Accuracy",
            "Precision",
            "Recall",
            "F1 Score",
            "ROC-AUC",
        ],
        "Logistic Regression": [
            list(cm_lr.ravel()),
            accuracy_score(y_test, lr_preds),
            precision_score(y_test, lr_preds),
            recall_score(y_test, lr_preds),
            f1_score(y_test, lr_preds),
            roc_auc_score(y_test, lr_probs),
        ],
        "Decision Tree": [
            list(cm_dt.ravel()),
            accuracy_score(y_test, dt_preds),
            precision_score(y_test, dt_preds),
            recall_score(y_test, dt_preds),
            f1_score(y_test, dt_preds),
            roc_auc_score(y_test, dt_probs),
        ],
    }
)

# Plot ROC Curves
fpr_lr, tpr_lr, _ = roc_curve(y_test, lr_probs)
fpr_dt, tpr_dt, _ = roc_curve(y_test, dt_probs)

plt.figure(figsize=(8, 6))
plt.plot(
    fpr_lr,
    tpr_lr,
    label=f"Logistic Regression (AUC = {roc_auc_score(y_test, lr_probs):.4f})",
    color="blue",
)
plt.plot(
    fpr_dt,
    tpr_dt,
    label=f"Decision Tree (AUC = {roc_auc_score(y_test, dt_probs):.4f})",
    color="red",
)
plt.plot([0, 1], [0, 1], "k--", label="Random Classifier (AUC = 0.5)")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend(loc="lower right")
plt.show()

import pandas as pd

# Predict default probabilities on the scaled test set
test_probs = lr_model.predict_proba(X_test_scaled)[:, 1]

# Create evaluation DataFrame
pricing_df = pd.DataFrame(
    {"actual_default": y_test.values, "predicted_prob": test_probs}
)

# Bucket into 4 probability quartiles
pricing_df["risk_tier"] = pd.qcut(
    pricing_df["predicted_prob"],
    q=4,
    labels=["Tier 1 (Low)", "Tier 2 (Med-Low)", "Tier 3 (Med-High)", "Tier 4 (High)"],
)

# Define illustrative interest rate ranges
apr_map = {
    "Tier 1 (Low)": "9.5% - 12.0%",
    "Tier 2 (Med-Low)": "12.5% - 15.5%",
    "Tier 3 (Med-High)": "16.0% - 20.0%",
    "Tier 4 (High)": "21.0% - 28.0%",
}

# Aggregate metrics per tier
tier_summary = (
    pricing_df.groupby("risk_tier", observed=False)
    .agg(
        applicant_count=("actual_default", "count"),
        min_prob=("predicted_prob", "min"),
        max_prob=("predicted_prob", "max"),
        observed_defaults=("actual_default", "sum"),
        observed_default_rate=("actual_default", "mean"),
    )
    .reset_index()
)

# Format pricing table output
tier_summary["observed_default_rate"] = (
    tier_summary["observed_default_rate"] * 100
).round(2).astype(str) + "%"
tier_summary["illustrative_apr"] = tier_summary["risk_tier"].map(apr_map)

print(tier_summary)

import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# 1. Load the dataset
df = pd.read_csv("txn_behaviour.csv")

# 2. Select numeric behavioural features
features = ["txn_hour", "is_new_device", "txn_amount_inr"]
X = df[features]

# 3. Standardize numeric features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4. Fit Isolation Forest with exact contamination rate (15 / 265)
contamination_rate = 15 / 265  # ~0.0566 (5.66%)
iso_forest = IsolationForest(contamination=contamination_rate, random_state=42)

# Predict (-1 indicates anomaly, 1 indicates normal)
df["anomaly_pred"] = iso_forest.fit_predict(X_scaled)
df["is_flagged"] = df["anomaly_pred"] == -1

# 5. Recall Check against Ground Truth (txn_id starting with 'BTXNA')
df["is_ground_truth_anomaly"] = df["txn_id"].astype(str).str.startswith("BTXNA")

total_seeded_anomalies = df["is_ground_truth_anomaly"].sum()
flagged_seeded_anomalies = (
    df["is_ground_truth_anomaly"] & df["is_flagged"]
).sum()
recall = (flagged_seeded_anomalies / total_seeded_anomalies) * 100

print(
    f"Seeded Anomalies Flagged: {flagged_seeded_anomalies} out of {total_seeded_anomalies}"
)
print(f"Anomaly Detection Recall: {recall:.2f}%")