# -*- coding: utf-8 -*-
"""generate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dYcKZSlDo4AOi3LHpBTiGImA2X8gIyQ
"""

import random
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

random.seed(42)
np.random.seed(42)

CATEGORIES = ["grocery", "food_delivery", "recharge", "bill_payment", "travel",
              "ecommerce", "entertainment"]
REGIONS = ["North", "South", "East", "West"]
METHODS = ["UPI", "Wallet", "Card", "Netbanking"]
METHOD_WEIGHTS = [0.55, 0.20, 0.15, 0.10]
AMOUNTS_INR = [49, 99, 149, 299, 499, 799, 1499, 2999, 4999]
AMOUNT_WEIGHTS = [0.18, 0.16, 0.14, 0.14, 0.12, 0.10, 0.08, 0.05, 0.03]

# --- 40 merchants ---
merchants = pd.DataFrame({
    "merchant_id": range(1, 41),
    "merchant_name": [f"Merchant_{i:03d}" for i in range(1, 41)],
    "category": [random.choice(CATEGORIES) for _ in range(40)],
    "region": [random.choice(REGIONS) for _ in range(40)],
})

# --- 350 established users, signed up 30-730 days before the window start ---
window_start = datetime(2026, 1, 1)
users = pd.DataFrame({
    "user_id": range(1, 351),
    "signup_date": [window_start - timedelta(days=random.randint(30, 730)) for _ in range(350)],
})

# --- 500 baseline transactions over a 30-day window ---
rows = []
for i in range(500):
    txn_time = window_start + timedelta(
        days=random.randint(0, 29), hours=random.randint(0, 23), minutes=random.randint(0, 59))
    status = np.random.choice(["captured", "failed", "chargeback"], p=[0.92, 0.06, 0.02])
    rows.append({
        "transaction_id": f"TXN{100000+i}",
        "user_id": random.randint(1, 350),
        "merchant_id": random.randint(1, 40),
        "transaction_time": txn_time,
        "amount_inr": np.random.choice(AMOUNTS_INR, p=AMOUNT_WEIGHTS),
        "payment_method": np.random.choice(METHODS, p=METHOD_WEIGHTS),
        "status": status,
        "risk_score": random.randint(0, 100),
    })

# --- inject 15 "burner account" chargeback frauds: brand-new users (< 30 days old) ---
next_user_id = 351
for i in range(15):
    txn_time = window_start + timedelta(days=random.randint(10, 29), hours=random.randint(0, 23))
    signup = txn_time - timedelta(days=random.randint(1, 25))
    users = pd.concat([users, pd.DataFrame([{"user_id": next_user_id, "signup_date": signup}])],
                       ignore_index=True)
    rows.append({
        "transaction_id": f"TXN{200000+i}",
        "user_id": next_user_id,
        "merchant_id": random.randint(1, 40),
        "transaction_time": txn_time,
        "amount_inr": random.choice([999, 1999, 2999, 4999]),
        "payment_method": "Card",
        "status": "chargeback",
        "risk_score": random.randint(70, 100),
    })
    next_user_id += 1

# --- inject 8 velocity-attack clusters: 4 rapid-fire txns each within a 5-minute window ---
for cluster in range(8):
    victim_user = random.randint(1, 350)
    base_time = window_start + timedelta(days=random.randint(0, 29), hours=random.randint(0, 23))
    for k in range(4):
        rows.append({
            "transaction_id": f"TXN{300000 + cluster*4 + k}",
            "user_id": victim_user,
            "merchant_id": random.randint(1, 40),
            "transaction_time": base_time + timedelta(minutes=k),
            "amount_inr": random.choice([299, 399, 499]),
            "payment_method": "Card",
            "status": "captured" if k == 3 else "failed",
            "risk_score": random.randint(60, 95),
        })

ledger = pd.DataFrame(rows)  # 500 + 15 + 32 = 547 rows
merchants.to_csv("merchants.csv", index=False)
users.to_csv("users.csv", index=False)
ledger.to_csv("ledger.csv", index=False)

# --- build the deliberately-discrepant "gateway export" copy for reconciliation ---
gateway = ledger.copy()
n = len(gateway)
missing_idx = np.random.choice(n, size=int(0.05 * n), replace=False)
gateway = gateway.drop(index=missing_idx).reset_index(drop=True)

mismatch_idx = np.random.choice(len(gateway), size=int(0.03 * n), replace=False)
gateway.loc[mismatch_idx, "amount_inr"] = gateway.loc[mismatch_idx, "amount_inr"] + \
    np.random.choice([-100, -50, 50, 100], size=len(mismatch_idx))

extra_rows = []
for i in range(int(0.02 * n)):
    extra_rows.append({
        "transaction_id": f"TXNX{9000+i}", "user_id": random.randint(1, 350),
        "merchant_id": random.randint(1, 40),
        "transaction_time": window_start + timedelta(days=random.randint(0, 29)),
        "amount_inr": random.choice(AMOUNTS_INR), "payment_method": random.choice(METHODS),
        "status": "captured", "risk_score": random.randint(0, 100),
    })
gateway = pd.concat([gateway, pd.DataFrame(extra_rows)], ignore_index=True)

status_idx = np.random.choice(len(gateway), size=int(0.02 * n), replace=False)
gateway.loc[status_idx, "status"] = "failed"

gateway.to_csv("gateway_export.csv", index=False)

import sqlite3
import pandas as pd

# 1. Connect to (or create) the SQLite database
conn = sqlite3.connect("paytm_payments.db")
cursor = conn.cursor()

# Enable foreign key constraint support in SQLite
cursor.execute("PRAGMA foreign_keys = ON;")

# 2. Create tables with normalized schema and constraints
cursor.executescript(
    """
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS merchants;

CREATE TABLE merchants (
    merchant_id INTEGER PRIMARY KEY,
    merchant_name TEXT,
    region TEXT,
    category TEXT
);

CREATE TABLE users (
    user_id INTEGER PRIMARY KEY,
    signup_date DATE
);

CREATE TABLE transactions (
    transaction_id TEXT PRIMARY KEY,
    user_id INTEGER,
    merchant_id INTEGER,
    transaction_time TIMESTAMP,
    amount_inr REAL,
    payment_method TEXT,
    status TEXT,
    risk_score REAL,
    MDR REAL,
    FOREIGN KEY (user_id) REFERENCES users (user_id),
    FOREIGN KEY (merchant_id) REFERENCES merchants (merchant_id)
);
"""
)

# 3. Read CSV files into pandas DataFrames
merchants_df = pd.read_csv("merchants.csv")
users_df = pd.read_csv("users.csv")
ledger_df = pd.read_csv("ledger.csv")

# 4. Load data into SQLite tables
merchants_df.to_sql("merchants", conn, if_exists="append", index=False)
users_df.to_sql("users", conn, if_exists="append", index=False)

# Rename table target from ledger to transactions
ledger_df.to_sql("transactions", conn, if_exists="append", index=False)

conn.commit()
conn.close()

print("Successfully created 'paytm_payments.db' and populated all tables!")

import pandas as pd


def reconcile_payments(ledger_df, gateway_df):
    """Reconciles internal ledger transactions against external gateway export.

    Returns:
        tuple: (missing_in_gateway, missing_in_ledger, amount_mismatches,
        status_mismatches)
    """
    # 1. Set operations for Missing Transactions
    ledger_ids = set(ledger_df["transaction_id"])
    gateway_ids = set(gateway_df["transaction_id"])

    missing_in_gateway_ids = ledger_ids - gateway_ids
    missing_in_ledger_ids = gateway_ids - ledger_ids

    missing_in_gateway = ledger_df[
        ledger_df["transaction_id"].isin(missing_in_gateway_ids)
    ].copy()
    missing_in_ledger = gateway_df[
        gateway_df["transaction_id"].isin(missing_in_ledger_ids)
    ].copy()

    # 2. Outer/Inner Merge for common records to find value/status discrepancies
    common_ids = ledger_ids & gateway_ids

    ledger_common = ledger_df[
        ledger_df["transaction_id"].isin(common_ids)
    ].copy()
    gateway_common = gateway_df[
        gateway_df["transaction_id"].isin(common_ids)
    ].copy()

    merged = pd.merge(
        ledger_common,
        gateway_common,
        on="transaction_id",
        suffixes=("_ledger", "_gateway"),
    )

    # 3. Amount Mismatches (with computed difference)
    # Using float rounding to prevent floating-point precision issues
    merged["amount_diff"] = (
        merged["amount_inr_ledger"] - merged["amount_inr_gateway"]
    ).round(2)
    amount_mismatches = merged[merged["amount_diff"] != 0].copy()

    # 4. Status Mismatches
    status_mismatches = merged[
        merged["status_ledger"] != merged["status_gateway"]
    ].copy()

    return (
        missing_in_gateway,
        missing_in_ledger,
        amount_mismatches,
        status_mismatches,
    )


# --- Execution and Reporting Block ---
if __name__ == "__main__":
    ledger_df = pd.read_csv("ledger.csv")
    gateway_df = pd.read_csv("gateway_export.csv")

    missing_gw, missing_ldg, amt_mismatch, status_mismatch = (
        reconcile_payments(ledger_df, gateway_df)
    )

    total_records = len(ledger_df)

    # Output discrepancy report with calculated rates
    print("=== PAYMENT RECONCILIATION DISCREPANCY REPORT ===")
    print(
        f"1. Missing in Gateway:  {len(missing_gw):>5} rows ({len(missing_gw)/total_records:.2%} vs ~5% target)"
    )
    print(
        f"2. Missing in Ledger:   {len(missing_ldg):>5} rows ({len(missing_ldg)/total_records:.2%} vs ~3% target)"
    )
    print(
        f"3. Amount Mismatches:   {len(amt_mismatch):>5} rows ({len(amt_mismatch)/total_records:.2%} vs ~2% target)"
    )
    print(
        f"4. Status Mismatches:   {len(status_mismatch):>5} rows ({len(status_mismatch)/total_records:.2%} vs ~2% target)"
    )