# -*- coding: utf-8 -*-
"""reconcile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPc_E0RZOFBjvv6fslQkfN-ml3ujcr14
"""

import pandas as pd


def reconcile_payments(ledger_df, gateway_df):
    """Reconciles internal ledger transactions against external gateway export.

    Returns:
        tuple: (missing_in_gateway, missing_in_ledger, amount_mismatches,
        status_mismatches)
    """
    # 1. Set operations for Missing Transactions
    ledger_ids = set(ledger_df["transaction_id"])
    gateway_ids = set(gateway_df["transaction_id"])

    missing_in_gateway_ids = ledger_ids - gateway_ids
    missing_in_ledger_ids = gateway_ids - ledger_ids

    missing_in_gateway = ledger_df[
        ledger_df["transaction_id"].isin(missing_in_gateway_ids)
    ].copy()
    missing_in_ledger = gateway_df[
        gateway_df["transaction_id"].isin(missing_in_ledger_ids)
    ].copy()

    # 2. Outer/Inner Merge for common records to find value/status discrepancies
    common_ids = ledger_ids & gateway_ids

    ledger_common = ledger_df[
        ledger_df["transaction_id"].isin(common_ids)
    ].copy()
    gateway_common = gateway_df[
        gateway_df["transaction_id"].isin(common_ids)
    ].copy()

    merged = pd.merge(
        ledger_common,
        gateway_common,
        on="transaction_id",
        suffixes=("_ledger", "_gateway"),
    )

    # 3. Amount Mismatches (with computed difference)
    # Using float rounding to prevent floating-point precision issues
    merged["amount_diff"] = (
        merged["amount_inr_ledger"] - merged["amount_inr_gateway"]
    ).round(2)
    amount_mismatches = merged[merged["amount_diff"] != 0].copy()

    # 4. Status Mismatches
    status_mismatches = merged[
        merged["status_ledger"] != merged["status_gateway"]
    ].copy()

    return (
        missing_in_gateway,
        missing_in_ledger,
        amount_mismatches,
        status_mismatches,
    )


# --- Execution and Reporting Block ---
if __name__ == "__main__":
    ledger_df = pd.read_csv("ledger.csv")
    gateway_df = pd.read_csv("gateway_export.csv")

    missing_gw, missing_ldg, amt_mismatch, status_mismatch = (
        reconcile_payments(ledger_df, gateway_df)
    )

    total_records = len(ledger_df)

    # Output discrepancy report with calculated rates
    print("=== PAYMENT RECONCILIATION DISCREPANCY REPORT ===")
    print(
        f"1. Missing in Gateway:  {len(missing_gw):>5} rows ({len(missing_gw)/total_records:.2%} vs ~5% target)"
    )
    print(
        f"2. Missing in Ledger:   {len(missing_ldg):>5} rows ({len(missing_ldg)/total_records:.2%} vs ~3% target)"
    )
    print(
        f"3. Amount Mismatches:   {len(amt_mismatch):>5} rows ({len(amt_mismatch)/total_records:.2%} vs ~2% target)"
    )
    print(
        f"4. Status Mismatches:   {len(status_mismatch):>5} rows ({len(status_mismatch)/total_records:.2%} vs ~2% target)"
    )

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Load Datasets
ledger_df = pd.read_csv("ledger.csv")
gateway_df = pd.read_csv("gateway_export.csv")
merchants_df = pd.read_csv("merchants.csv")

# Format Timestamps
ledger_df["transaction_time"] = pd.to_datetime(ledger_df["transaction_time"])
ledger_df["Date"] = ledger_df["transaction_time"].dt.date

# Create Master Merged Dataset
master_df = ledger_df.merge(merchants_df, on="merchant_id", how="left")

# Setup Matplotlib Figure Grid
fig = plt.figure(figsize=(16, 20), dpi=300)
fig.suptitle(
    "Paytm Executive Payments & Risk Dashboard",
    fontsize=22,
    fontweight="bold",
    y=0.98,
)

# ==========================================
# LAYER 1: HEADLINE SCORECARDS
# ==========================================
# Metrics Calculations
total_gmv = ledger_df["amount_inr"].sum()
overall_success_rate = (
    ledger_df["status"] == "captured"
).mean() * 100  # Percentage
platform_chargeback_ratio = (
    ledger_df["status"] == "chargeback"
).mean() * 100  # Percentage

# Match Rate Metric Calculation
reconciled_inner = pd.merge(
    ledger_df,
    gateway_df,
    on="transaction_id",
    suffixes=("_ledger", "_gateway"),
)
matched_rows = reconciled_inner[
    (reconciled_inner["amount_inr_ledger"] == reconciled_inner["amount_inr_gateway"])
    & (reconciled_inner["status_ledger"] == reconciled_inner["status_gateway"])
]
match_rate = (len(matched_rows) / len(ledger_df)) * 100

# Plot Headline Cards
scorecards = [
    ("Total GMV", f"₹{total_gmv:,.0f}", "#1E3A8A"),
    ("Success Rate", f"{overall_success_rate:.2f}%", "#16A34A"),
    ("Reconciliation Match Rate", f"{match_rate:.2f}%", "#D97706"),
    ("Chargeback Ratio", f"{platform_chargeback_ratio:.2f}%", "#DC2626"),
]

for idx, (title, val, color) in enumerate(scorecards):
    ax = fig.add_subplot(5, 4, idx + 1)
    ax.axis("off")
    ax.add_patch(
        plt.Rectangle(
            (0.05, 0.05),
            0.9,
            0.9,
            fill=True,
            color="#F3F4F6",
            ec=color,
            lw=2,
            transform=ax.transAxes,
        )
    )
    ax.text(
        0.5,
        0.65,
        title,
        fontsize=11,
        fontweight="bold",
        ha="center",
        va="center",
        transform=ax.transAxes,
        color="#374151",
    )
    ax.text(
        0.5,
        0.35,
        val,
        fontsize=16,
        fontweight="bold",
        ha="center",
        va="center",
        transform=ax.transAxes,
        color=color,
    )

# ==========================================
# LAYER 2: TRENDS LAYER (Time-Series)
# ==========================================
daily_stats = (
    ledger_df.groupby("Date")
    .agg(
        daily_gmv=("amount_inr", "sum"),
        chargeback_count=(
            "status",
            lambda x: (x == "chargeback").sum(),
        ),
    )
    .reset_index()
)

ax1 = fig.add_subplot(5, 1, 2)
ax2 = ax1.twinx()

line1 = ax1.plot(
    daily_stats["Date"],
    daily_stats["daily_gmv"] / 1e3,
    color="#1E3A8A",
    linewidth=2.5,
    label="Daily GMV (k INR)",
)
line2 = ax2.plot(
    daily_stats["Date"],
    daily_stats["chargeback_count"],
    color="#DC2626",
    linewidth=2,
    linestyle="--",
    label="Daily Chargebacks",
)

ax1.set_ylabel("Daily GMV (in '000 INR)", color="#1E3A8A", fontweight="bold")
ax2.set_ylabel("Chargeback Count", color="#DC2626", fontweight="bold")
ax1.set_title(
    "30-Day Trend: Daily GMV vs. Chargeback Volume",
    fontsize=14,
    fontweight="bold",
    pad=10,
)
ax1.grid(True, linestyle=":", alpha=0.6)

# Combine legends
lines = line1 + line2
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc="upper left")

# ==========================================
# LAYER 3: BREAKDOWN LAYER (Bar Charts)
# ==========================================
# GMV by Payment Method
pm_gmv = (
    master_df.groupby("payment_method")["amount_inr"].sum().sort_values(ascending=False)
)
ax_pm = fig.add_subplot(5, 2, 5)
pm_gmv.plot(kind="bar", ax=ax_pm, color="#3B82F6", edgecolor="black")
ax_pm.set_title("GMV Breakdown by Payment Method", fontweight="bold")
ax_pm.set_ylabel("GMV (INR)")
ax_pm.set_xticklabels(ax_pm.get_xticklabels(), rotation=45, ha="right")
ax_pm.grid(axis="y", linestyle=":", alpha=0.6)

# GMV by Merchant Category
cat_gmv = (
    master_df.groupby("category")["amount_inr"].sum().sort_values(ascending=False)
)
ax_cat = fig.add_subplot(5, 2, 6)
cat_gmv.plot(kind="bar", ax=ax_cat, color="#10B981", edgecolor="black")
ax_cat.set_title("GMV Breakdown by Merchant Category", fontweight="bold")
ax_cat.set_ylabel("GMV (INR)")
ax_cat.set_xticklabels(ax_cat.get_xticklabels(), rotation=45, ha="right")
ax_cat.grid(axis="y", linestyle=":", alpha=0.6)

# ==========================================
# LAYER 4: DETAILS LAYER (Top 10 Table Image)
# ==========================================
top10_merchants = (
    master_df.groupby(["merchant_id", "merchant_name"])
    .agg(
        total_txns=("transaction_id", "count"),
        chargeback_count=(
            "status",
            lambda x: (x == "chargeback").sum(),
        ),
        total_gmv=("amount_inr", "sum"),
    )
    .reset_index()
)

top10_merchants["chargeback_ratio"] = (
    top10_merchants["chargeback_count"] / top10_merchants["total_txns"]
) * 100
top10_merchants["flag"] = np.where(
    top10_merchants["chargeback_ratio"] > 1.0, "HIGH RISK", "NORMAL"
)

# Sort and slice top 10 by count
top10_table = top10_merchants.sort_values(
    by="total_txns", ascending=False
).head(10)

ax_tbl = fig.add_subplot(5, 1, 5)
ax_tbl.axis("off")
ax_tbl.set_title(
    "Top 10 Merchants by Transaction Count (Risk Flag > 1.0% Chargeback Ratio)",
    fontweight="bold",
    pad=15,
)

# Table Formatting
table_data = []
for _, row in top10_table.iterrows():
    table_data.append([
        int(row["merchant_id"]),
        str(row["merchant_name"]),
        f"{row['total_txns']:,}",
        f"₹{row['total_gmv']:,.2f}",
        f"{row['chargeback_ratio']:.2f}%",
        row["flag"],
    ])

col_headers = [
    "Merchant ID",
    "Name",
    "Txn Count",
    "Total GMV",
    "Chargeback Ratio",
    "Risk Flag",
]
tbl = ax_tbl.table(
    cellText=table_data,
    colLabels=col_headers,
    loc="center",
    cellLoc="center",
)
tbl.auto_set_font_size(False)
tbl.set_fontsize(10)
tbl.scale(1.2, 1.6)

# Highlight high-risk rows
for row_idx, row in enumerate(top10_table.itertuples(), start=1):
    if row.flag == "HIGH RISK":
        for col_idx in range(len(col_headers)):
            tbl[(row_idx, col_idx)].set_facecolor("#FEE2E2")  # Light red tint
            tbl[(row_idx, col_idx)].get_text().set_color("#991B1B")
            tbl[(row_idx, col_idx)].get_text().set_weight("bold")

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig("payments_dashboard.png", dpi=300)
plt.show()
