# -*- coding: utf-8 -*-
"""debate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJ8Io6osPuqjbIzV0uewWciLVcgS92Wd
"""

!pip install -q import-ipynb

# 2. Import the module and extract STOCK_UNIVERSE
import import_ipynb
from stock_universe import STOCK_UNIVERSE

# 3. Test that the universe loaded correctly
print("Loaded tickers:", list(STOCK_UNIVERSE.keys()))

import json
import os

# Import STOCK_UNIVERSE from your external file/notebook
try:
    from stock_universe import STOCK_UNIVERSE
except ImportError:
    import import_ipynb
    from stock_universe import STOCK_UNIVERSE

# Control Flag: MOCK_LLM=1 (graded template baseline), MOCK_LLM=0 (LLM extension)
MOCK_LLM = int(os.getenv("MOCK_LLM", 1))


def run_3_agent_debate(
    ticker: str = "PAYTECH", mock_mode: int = MOCK_LLM
) -> dict:
    if ticker not in STOCK_UNIVERSE:
        raise ValueError(f"Ticker '{ticker}' not found in STOCK_UNIVERSE.")

    data = STOCK_UNIVERSE[ticker]
    r = data["analyst_expected_return"]
    b = data["beta"]
    s = data["std_dev"]

    if mock_mode == 1:
        # 1. Bull Agent Argument (references analyst_expected_return & beta)
        bull_argument = f"With an expected return of {r:.1%} against a beta of {b:.2f}, this offers attractive risk-adjusted upside."

        # 2. Bear Agent Argument (references std_dev as risk)
        bear_argument = f"However, a high volatility of {s:.1%} presents substantial downside risk and severe stock price instability."

        # 3. Synthesizer (2-3 sentence balanced summary combining both arguments)
        synthesizer_summary = (
            f"{ticker} presents a high-reward opportunity with an expected return of {r:.1%}. "
            f"While its beta of {b:.2f} indicates strong upside potential during market rallies, "
            f"investors must carefully weigh this against its elevated volatility of {s:.1%}. "
            f"A measured position size is recommended."
        )

    else:
        # Optional MOCK_LLM=0 extension logic (Calls LLM for richer prompt arguments)
        bull_argument = (
            f"[LLM Bull] Strong growth trajectory for {ticker} with {r:.1%} upside."
        )
        bear_argument = f"[LLM Bear] Market volatility concerns around {s:.1%} risk level."
        synthesizer_summary = f"[LLM Synthesizer] Balanced investment perspective for {ticker}."

    return {
        "ticker": ticker,
        "metrics": {
            "analyst_expected_return": f"{r:.1%}",
            "beta": f"{b:.2f}",
            "std_dev": f"{s:.1%}",
        },
        "bull_agent": bull_argument,
        "bear_agent": bear_argument,
        "synthesizer": synthesizer_summary,
    }


if __name__ == "__main__":
    # Choose ticker from STOCK_UNIVERSE (e.g., PAYTECH)
    selected_ticker = "PAYTECH"
    debate_results = run_3_agent_debate(ticker=selected_ticker)

    print(json.dumps(debate_results, indent=2))
