# -*- coding: utf-8 -*-
"""extract_disclosure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xq-lX7ep7VZH1oJAuknvSOPfeRjxM9BD
"""

import os
import re
import json

# Import DISCLOSURE_SNIPPETS from the external file/notebook
# (Uses import-ipynb if disclosure_snippets is a .ipynb file)
try:
    from disclosure_snippets import DISCLOSURE_SNIPPETS
except ImportError:
    import import_ipynb
    from disclosure_snippets import DISCLOSURE_SNIPPETS

# Control flag: MOCK_LLM=1 (graded baseline), MOCK_LLM=0 (LLM extension)
MOCK_LLM = int(os.getenv("MOCK_LLM", 1))


def extract_signals_mock(snippet: str) -> dict:
    """Mock mode (graded baseline) using keyword/regex rule extraction."""
    snippet_lower = snippet.lower()

    # 1. Flag risk keywords/phrases
    risk_flags = []
    if "litigation" in snippet_lower:
        risk_flags.append("litigation")
    if "regulatory" in snippet_lower or "regulator" in snippet_lower:
        risk_flags.append("regulatory")
    if re.search(
        r"top \w+ customers|percent of total revenue|customer concentration",
        snippet_lower,
    ):
        risk_flags.append("customer concentration")

    # 2. Flag hedging phrases containing "assuming", "cautiously", or "visibility"
    hedging_keywords = ["assuming", "cautiously", "visibility"]
    hedging_detected = any(kw in snippet_lower for kw in hedging_keywords)

    # 3. Classify sentiment: "confident", "cautious", or "neutral"
    if "confident" in snippet_lower or "approved" in snippet_lower:
        sentiment = "confident"
    elif hedging_detected:
        sentiment = "cautious"
    else:
        sentiment = "neutral"

    return {
        "risk_flags": risk_flags,
        "hedging_detected": hedging_detected,
        "sentiment": sentiment,
    }


def validate_schema(data: dict) -> bool:
    """Validates that extracted dictionary adheres strictly to the target schema."""
    if not isinstance(data, dict):
        return False
    if "risk_flags" not in data or not isinstance(data["risk_flags"], list):
        return False
    if "hedging_detected" not in data or not isinstance(
        data["hedging_detected"], bool
    ):
        return False
    if "sentiment" not in data or data["sentiment"] not in [
        "confident",
        "cautious",
        "neutral",
    ]:
        return False
    return True


def extract_signals(snippet: str, mock_mode: int = MOCK_LLM) -> dict:
    """Extracts structured disclosure signals with schema validation and fallback."""
    if mock_mode == 1:
        return extract_signals_mock(snippet)

    # MOCK_LLM = 0 (Optional LLM extension with retry and fallback)
    for _ in range(2):
        try:
            # Place actual LLM call here if using API
            llm_response = {}
            if validate_schema(llm_response):
                return llm_response
        except Exception:
            pass

    # Fall back to mock result if LLM fails or fails validation
    return extract_signals_mock(snippet)


# Batch execution across all 6 imported snippets
if __name__ == "__main__":
    extracted_results = {}

    for snippet in DISCLOSURE_SNIPPETS:
        doc_id = snippet.split(":")[0]
        extracted_results[doc_id] = extract_signals(snippet)

    print(json.dumps(extracted_results, indent=2))
